<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<!-- git web interface version 2.23.0, (C) 2005-2006, Kay Sievers <kay.sievers@vrfy.org>, Christian Gierke -->
<!-- git core binaries version 2.23.0 -->
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta name="generator" content="gitweb/2.23.0 git/2.23.0"/>
<meta name="robots" content="index, nofollow"/>
<title>git.blender.org - blender-addons-contrib.git/blob - add_mesh_rocks/randomize_texture.py</title>
<base href="https://git.blender.org/gitweb/gitweb.cgi" />
<link rel="stylesheet" type="text/css" href="static/gitweb.css"/>
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/randomize_texture.py - RSS feed" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/randomize_texture.py" type="application/rss+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/randomize_texture.py - RSS feed (no merges)" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/randomize_texture.py;opt=--no-merges" type="application/rss+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/randomize_texture.py - Atom feed" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/randomize_texture.py" type="application/atom+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/randomize_texture.py - Atom feed (no merges)" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/randomize_texture.py;opt=--no-merges" type="application/atom+xml" />
<link rel="shortcut icon" href="static/git-favicon.png" type="image/png" />
</head>
<body>
<div class="page_header">
<a href="http://git-scm.com/" title="git homepage"><img alt="git" class="logo" height="27" src="static/git-logo.png" width="72" /></a><a href="https://git.blender.org/gitweb/">projects</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git">blender-addons-contrib.git</a> / blob
</div>
<div class="page_nav">
<a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git">summary</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/shortlog">shortlog</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/log">log</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commit/HEAD">commit</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commitdiff/HEAD">commitdiff</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD">tree</a><br/>
<a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/history/HEAD:/add_mesh_rocks/randomize_texture.py">history</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob_plain/HEAD:/add_mesh_rocks/randomize_texture.py">raw</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py">HEAD</a><br/>
</div>
<div class="header">
<a class="title" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commit/HEAD">Collection Manager: Update Tooltips. Task: T69577</a>
</div>
<div class="page_path"><a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD" title="tree root">[blender-addons-contrib.git]</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD:/add_mesh_rocks" title="add_mesh_rocks">add_mesh_rocks</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob_plain/HEAD:/add_mesh_rocks/randomize_texture.py" title="add_mesh_rocks/randomize_texture.py">randomize_texture.py</a><br/></div>
<div class="page_body">
<div class="pre"><a id="l1" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l1" class="linenr">   1</a> #&nbsp;This&nbsp;try&nbsp;block&nbsp;allows&nbsp;for&nbsp;the&nbsp;script&nbsp;to&nbsp;psudo-intelligently&nbsp;select&nbsp;the</div>
<div class="pre"><a id="l2" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l2" class="linenr">   2</a> #&nbsp;appropriate&nbsp;random&nbsp;to&nbsp;use.&nbsp;&nbsp;If&nbsp;Numpy&#39;s&nbsp;random&nbsp;is&nbsp;present&nbsp;it&nbsp;will&nbsp;use&nbsp;that.</div>
<div class="pre"><a id="l3" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l3" class="linenr">   3</a> #&nbsp;If&nbsp;Numpy&#39;s&nbsp;random&nbsp;is&nbsp;not&nbsp;present,&nbsp;it&nbsp;will&nbsp;through&nbsp;a&nbsp;&quot;module&nbsp;not&nbsp;found&quot;</div>
<div class="pre"><a id="l4" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l4" class="linenr">   4</a> #&nbsp;exception&nbsp;and&nbsp;instead&nbsp;use&nbsp;the&nbsp;slower&nbsp;built-in&nbsp;random&nbsp;that&nbsp;Python&nbsp;has.</div>
<div class="pre"><a id="l5" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l5" class="linenr">   5</a> try:</div>
<div class="pre"><a id="l6" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l6" class="linenr">   6</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;numpy.random&nbsp;import&nbsp;random_integers&nbsp;as&nbsp;randint</div>
<div class="pre"><a id="l7" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l7" class="linenr">   7</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;numpy.random&nbsp;import&nbsp;normal&nbsp;as&nbsp;gauss</div>
<div class="pre"><a id="l8" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l8" class="linenr">   8</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;numpy.random&nbsp;import&nbsp;(</div>
<div class="pre"><a id="l9" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l9" class="linenr">   9</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;beta,</div>
<div class="pre"><a id="l10" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l10" class="linenr">  10</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uniform,</div>
<div class="pre"><a id="l11" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l11" class="linenr">  11</a> &nbsp;&nbsp;&nbsp;&nbsp;)</div>
<div class="pre"><a id="l12" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l12" class="linenr">  12</a> except:</div>
<div class="pre"><a id="l13" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l13" class="linenr">  13</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;random&nbsp;import&nbsp;(</div>
<div class="pre"><a id="l14" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l14" class="linenr">  14</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;randint,</div>
<div class="pre"><a id="l15" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l15" class="linenr">  15</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gauss,</div>
<div class="pre"><a id="l16" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l16" class="linenr">  16</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uniform,</div>
<div class="pre"><a id="l17" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l17" class="linenr">  17</a> &nbsp;&nbsp;&nbsp;&nbsp;)</div>
<div class="pre"><a id="l18" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l18" class="linenr">  18</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;random&nbsp;import&nbsp;betavariate&nbsp;as&nbsp;beta</div>
<div class="pre"><a id="l19" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l19" class="linenr">  19</a> </div>
<div class="pre"><a id="l20" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l20" class="linenr">  20</a> from&nbsp;add_mesh_rocks.utils&nbsp;import&nbsp;skewedGauss</div>
<div class="pre"><a id="l21" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l21" class="linenr">  21</a> </div>
<div class="pre"><a id="l22" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l22" class="linenr">  22</a> </div>
<div class="pre"><a id="l23" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l23" class="linenr">  23</a> def&nbsp;randomizeTexture(texture,&nbsp;level=1):</div>
<div class="pre"><a id="l24" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l24" class="linenr">  24</a> &nbsp;&nbsp;&nbsp;&nbsp;&#39;&#39;&#39;</div>
<div class="pre"><a id="l25" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l25" class="linenr">  25</a> &nbsp;&nbsp;&nbsp;&nbsp;Set&nbsp;the&nbsp;values&nbsp;for&nbsp;a&nbsp;texture&nbsp;from&nbsp;parameters.</div>
<div class="pre"><a id="l26" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l26" class="linenr">  26</a> </div>
<div class="pre"><a id="l27" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l27" class="linenr">  27</a> &nbsp;&nbsp;&nbsp;&nbsp;param:&nbsp;texture&nbsp;-&nbsp;bpy.data.texture&nbsp;to&nbsp;modify.</div>
<div class="pre"><a id="l28" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l28" class="linenr">  28</a> &nbsp;&nbsp;&nbsp;&nbsp;level&nbsp;&nbsp;&nbsp;-&nbsp;designated&nbsp;tweaked&nbsp;settings&nbsp;to&nbsp;use</div>
<div class="pre"><a id="l29" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l29" class="linenr">  29</a> &nbsp;&nbsp;&nbsp;&nbsp;-&gt;&nbsp;Below&nbsp;10&nbsp;is&nbsp;a&nbsp;displacment&nbsp;texture</div>
<div class="pre"><a id="l30" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l30" class="linenr">  30</a> &nbsp;&nbsp;&nbsp;&nbsp;-&gt;&nbsp;Between&nbsp;10&nbsp;and&nbsp;20&nbsp;is&nbsp;a&nbsp;base&nbsp;material&nbsp;texture</div>
<div class="pre"><a id="l31" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l31" class="linenr">  31</a> &nbsp;&nbsp;&nbsp;&nbsp;&#39;&#39;&#39;</div>
<div class="pre"><a id="l32" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l32" class="linenr">  32</a> &nbsp;&nbsp;&nbsp;&nbsp;noises&nbsp;=&nbsp;[&#39;BLENDER_ORIGINAL&#39;,&nbsp;&#39;ORIGINAL_PERLIN&#39;,&nbsp;&#39;IMPROVED_PERLIN&#39;,</div>
<div class="pre"><a id="l33" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l33" class="linenr">  33</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#39;VORONOI_F1&#39;,&nbsp;&#39;VORONOI_F2&#39;,&nbsp;&#39;VORONOI_F3&#39;,&nbsp;&#39;VORONOI_F4&#39;,</div>
<div class="pre"><a id="l34" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l34" class="linenr">  34</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#39;VORONOI_F2_F1&#39;,&nbsp;&#39;VORONOI_CRACKLE&#39;]</div>
<div class="pre"><a id="l35" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l35" class="linenr">  35</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;texture.type&nbsp;==&nbsp;&#39;CLOUDS&#39;:</div>
<div class="pre"><a id="l36" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l36" class="linenr">  36</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;randint(0,&nbsp;1)&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l37" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l37" class="linenr">  37</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_type&nbsp;=&nbsp;&#39;SOFT_NOISE&#39;</div>
<div class="pre"><a id="l38" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l38" class="linenr">  38</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l39" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l39" class="linenr">  39</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_type&nbsp;=&nbsp;&#39;HARD_NOISE&#39;</div>
<div class="pre"><a id="l40" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l40" class="linenr">  40</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;level&nbsp;!=&nbsp;11:</div>
<div class="pre"><a id="l41" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l41" class="linenr">  41</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l42" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l42" class="linenr">  42</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l43" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l43" class="linenr">  43</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;8)</div>
<div class="pre"><a id="l44" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l44" class="linenr">  44</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_basis&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l45" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l45" class="linenr">  45</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_depth&nbsp;=&nbsp;8</div>
<div class="pre"><a id="l46" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l46" class="linenr">  46</a> </div>
<div class="pre"><a id="l47" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l47" class="linenr">  47</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;level&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l48" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l48" class="linenr">  48</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.625,&nbsp;1&nbsp;/&nbsp;24)</div>
<div class="pre"><a id="l49" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l49" class="linenr">  49</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;2:</div>
<div class="pre"><a id="l50" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l50" class="linenr">  50</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;0.15</div>
<div class="pre"><a id="l51" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l51" class="linenr">  51</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;11:</div>
<div class="pre"><a id="l52" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l52" class="linenr">  52</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.5,&nbsp;1&nbsp;/&nbsp;24)</div>
<div class="pre"><a id="l53" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l53" class="linenr">  53</a> </div>
<div class="pre"><a id="l54" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l54" class="linenr">  54</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;texture.noise_basis&nbsp;in&nbsp;[&#39;BLENDER_ORIGINAL&#39;,&nbsp;&#39;ORIGINAL_PERLIN&#39;,</div>
<div class="pre"><a id="l55" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l55" class="linenr">  55</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#39;IMPROVED_PERLIN&#39;,&nbsp;&#39;VORONOI_F1&#39;]:</div>
<div class="pre"><a id="l56" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l56" class="linenr">  56</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(1,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l57" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l57" class="linenr">  57</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;gauss(4,&nbsp;1&nbsp;/&nbsp;3)</div>
<div class="pre"><a id="l58" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l58" class="linenr">  58</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.noise_basis&nbsp;in&nbsp;[&#39;VORONOI_F2&#39;,&nbsp;&#39;VORONOI_F3&#39;,&nbsp;&#39;VORONOI_F4&#39;]:</div>
<div class="pre"><a id="l59" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l59" class="linenr">  59</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(0.25,&nbsp;1&nbsp;/&nbsp;12)</div>
<div class="pre"><a id="l60" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l60" class="linenr">  60</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;gauss(2,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l61" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l61" class="linenr">  61</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.noise_basis&nbsp;==&nbsp;&#39;VORONOI_F2_F1&#39;:</div>
<div class="pre"><a id="l62" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l62" class="linenr">  62</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(0.5,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l63" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l63" class="linenr">  63</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;gauss(2,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l64" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l64" class="linenr">  64</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.noise_basis&nbsp;==&nbsp;&#39;VORONOI_CRACKLE&#39;:</div>
<div class="pre"><a id="l65" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l65" class="linenr">  65</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(0.5,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l66" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l66" class="linenr">  66</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;gauss(2,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l67" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l67" class="linenr">  67</a> &nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.type&nbsp;==&nbsp;&#39;MUSGRAVE&#39;:</div>
<div class="pre"><a id="l68" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l68" class="linenr">  68</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;musgraveType&nbsp;=&nbsp;[&#39;MULTIFRACTAL&#39;,&nbsp;&#39;RIDGED_MULTIFRACTAL&#39;,</div>
<div class="pre"><a id="l69" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l69" class="linenr">  69</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#39;HYBRID_MULTIFRACTAL&#39;,&nbsp;&#39;FBM&#39;,&nbsp;&#39;HETERO_TERRAIN&#39;]</div>
<div class="pre"><a id="l70" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l70" class="linenr">  70</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.musgrave_type&nbsp;=&nbsp;&#39;MULTIFRACTAL&#39;</div>
<div class="pre"><a id="l71" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l71" class="linenr">  71</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.dimension_max&nbsp;=&nbsp;abs(gauss(0,&nbsp;0.6))&nbsp;+&nbsp;0.2</div>
<div class="pre"><a id="l72" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l72" class="linenr">  72</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.lacunarity&nbsp;=&nbsp;beta(3,&nbsp;8)&nbsp;*&nbsp;8.2&nbsp;+&nbsp;1.8</div>
<div class="pre"><a id="l73" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l73" class="linenr">  73</a> </div>
<div class="pre"><a id="l74" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l74" class="linenr">  74</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;level&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l75" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l75" class="linenr">  75</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.625,&nbsp;1&nbsp;/&nbsp;24)</div>
<div class="pre"><a id="l76" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l76" class="linenr">  76</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_intensity&nbsp;=&nbsp;0.2</div>
<div class="pre"><a id="l77" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l77" class="linenr">  77</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.octaves&nbsp;=&nbsp;1.0</div>
<div class="pre"><a id="l78" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l78" class="linenr">  78</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;2:</div>
<div class="pre"><a id="l79" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l79" class="linenr">  79</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(1,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l80" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l80" class="linenr">  80</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;0.2</div>
<div class="pre"><a id="l81" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l81" class="linenr">  81</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;0.15</div>
<div class="pre"><a id="l82" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l82" class="linenr">  82</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.octaves&nbsp;=&nbsp;8.0</div>
<div class="pre"><a id="l83" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l83" class="linenr">  83</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;10:</div>
<div class="pre"><a id="l84" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l84" class="linenr">  84</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(0.25,&nbsp;1&nbsp;/&nbsp;12)</div>
<div class="pre"><a id="l85" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l85" class="linenr">  85</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;gauss(1.5,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l86" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l86" class="linenr">  86</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;0.5</div>
<div class="pre"><a id="l87" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l87" class="linenr">  87</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.octaves&nbsp;=&nbsp;8.0</div>
<div class="pre"><a id="l88" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l88" class="linenr">  88</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;12:</div>
<div class="pre"><a id="l89" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l89" class="linenr">  89</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.octaves&nbsp;=&nbsp;uniform(1,&nbsp;3)</div>
<div class="pre"><a id="l90" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l90" class="linenr">  90</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;&gt;&nbsp;12:</div>
<div class="pre"><a id="l91" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l91" class="linenr">  91</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.octaves&nbsp;=&nbsp;uniform(2,&nbsp;8)</div>
<div class="pre"><a id="l92" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l92" class="linenr">  92</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l93" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l93" class="linenr">  93</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;gauss(1,&nbsp;1&nbsp;/&nbsp;6)</div>
<div class="pre"><a id="l94" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l94" class="linenr">  94</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;0.2</div>
<div class="pre"><a id="l95" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l95" class="linenr">  95</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.octaves&nbsp;=&nbsp;8.0</div>
<div class="pre"><a id="l96" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l96" class="linenr">  96</a> &nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.type&nbsp;==&nbsp;&#39;DISTORTED_NOISE&#39;:</div>
<div class="pre"><a id="l97" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l97" class="linenr">  97</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;8)</div>
<div class="pre"><a id="l98" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l98" class="linenr">  98</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_distortion&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l99" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l99" class="linenr">  99</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;8)</div>
<div class="pre"><a id="l100" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l100" class="linenr"> 100</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_basis&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l101" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l101" class="linenr"> 101</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.distortion&nbsp;=&nbsp;skewedGauss(2.0,&nbsp;2.6666,&nbsp;(0.0,&nbsp;10.0),&nbsp;False)</div>
<div class="pre"><a id="l102" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l102" class="linenr"> 102</a> </div>
<div class="pre"><a id="l103" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l103" class="linenr"> 103</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;level&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l104" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l104" class="linenr"> 104</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.625,&nbsp;1&nbsp;/&nbsp;24)</div>
<div class="pre"><a id="l105" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l105" class="linenr"> 105</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;2:</div>
<div class="pre"><a id="l106" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l106" class="linenr"> 106</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;0.15</div>
<div class="pre"><a id="l107" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l107" class="linenr"> 107</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;&gt;=&nbsp;12:</div>
<div class="pre"><a id="l108" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l108" class="linenr"> 108</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.2,&nbsp;1&nbsp;/&nbsp;48)</div>
<div class="pre"><a id="l109" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l109" class="linenr"> 109</a> &nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.type&nbsp;==&nbsp;&#39;STUCCI&#39;:</div>
<div class="pre"><a id="l110" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l110" class="linenr"> 110</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stucciTypes&nbsp;=&nbsp;[&#39;PLASTIC&#39;,&nbsp;&#39;WALL_IN&#39;,&nbsp;&#39;WALL_OUT&#39;]</div>
<div class="pre"><a id="l111" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l111" class="linenr"> 111</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;randint(0,&nbsp;1)&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l112" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l112" class="linenr"> 112</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_type&nbsp;=&nbsp;&#39;SOFT_NOISE&#39;</div>
<div class="pre"><a id="l113" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l113" class="linenr"> 113</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l114" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l114" class="linenr"> 114</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_type&nbsp;=&nbsp;&#39;HARD_NOISE&#39;</div>
<div class="pre"><a id="l115" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l115" class="linenr"> 115</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;2)</div>
<div class="pre"><a id="l116" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l116" class="linenr"> 116</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.stucci_type&nbsp;=&nbsp;stucciTypes[tempInt]</div>
<div class="pre"><a id="l117" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l117" class="linenr"> 117</a> </div>
<div class="pre"><a id="l118" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l118" class="linenr"> 118</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;level&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l119" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l119" class="linenr"> 119</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l120" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l120" class="linenr"> 120</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_basis&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l121" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l121" class="linenr"> 121</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.625,&nbsp;1&nbsp;/&nbsp;24)</div>
<div class="pre"><a id="l122" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l122" class="linenr"> 122</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;2:</div>
<div class="pre"><a id="l123" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l123" class="linenr"> 123</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l124" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l124" class="linenr"> 124</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_basis&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l125" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l125" class="linenr"> 125</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;0.15</div>
<div class="pre"><a id="l126" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l126" class="linenr"> 126</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;&gt;=&nbsp;12:</div>
<div class="pre"><a id="l127" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l127" class="linenr"> 127</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l128" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l128" class="linenr"> 128</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_basis&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l129" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l129" class="linenr"> 129</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.2,&nbsp;1&nbsp;/&nbsp;30)</div>
<div class="pre"><a id="l130" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l130" class="linenr"> 130</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l131" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l131" class="linenr"> 131</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l132" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l132" class="linenr"> 132</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_basis&nbsp;=&nbsp;noises[tempInt]</div>
<div class="pre"><a id="l133" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l133" class="linenr"> 133</a> &nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;texture.type&nbsp;==&nbsp;&#39;VORONOI&#39;:</div>
<div class="pre"><a id="l134" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l134" class="linenr"> 134</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;metrics&nbsp;=&nbsp;[&#39;DISTANCE&#39;,&nbsp;&#39;DISTANCE_SQUARED&#39;,&nbsp;&#39;MANHATTAN&#39;,&nbsp;&#39;CHEBYCHEV&#39;,</div>
<div class="pre"><a id="l135" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l135" class="linenr"> 135</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#39;MINKOVSKY_HALF&#39;,&nbsp;&#39;MINKOVSKY_FOUR&#39;,&nbsp;&#39;MINKOVSKY&#39;]</div>
<div class="pre"><a id="l136" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l136" class="linenr"> 136</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Settings&nbsp;for&nbsp;first&nbsp;dispalcement&nbsp;level:</div>
<div class="pre"><a id="l137" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l137" class="linenr"> 137</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;level&nbsp;==&nbsp;0:</div>
<div class="pre"><a id="l138" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l138" class="linenr"> 138</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;1)</div>
<div class="pre"><a id="l139" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l139" class="linenr"> 139</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.distance_metric&nbsp;=&nbsp;metrics[tempInt]</div>
<div class="pre"><a id="l140" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l140" class="linenr"> 140</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.625,&nbsp;1&nbsp;/&nbsp;24)</div>
<div class="pre"><a id="l141" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l141" class="linenr"> 141</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;0.5</div>
<div class="pre"><a id="l142" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l142" class="linenr"> 142</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;0.7</div>
<div class="pre"><a id="l143" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l143" class="linenr"> 143</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;==&nbsp;2:</div>
<div class="pre"><a id="l144" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l144" class="linenr"> 144</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;0.15</div>
<div class="pre"><a id="l145" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l145" class="linenr"> 145</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l146" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l146" class="linenr"> 146</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.distance_metric&nbsp;=&nbsp;metrics[tempInt]</div>
<div class="pre"><a id="l147" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l147" class="linenr"> 147</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;level&nbsp;&gt;=&nbsp;12:</div>
<div class="pre"><a id="l148" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l148" class="linenr"> 148</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;1)</div>
<div class="pre"><a id="l149" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l149" class="linenr"> 149</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.distance_metric&nbsp;=&nbsp;metrics[tempInt]</div>
<div class="pre"><a id="l150" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l150" class="linenr"> 150</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.noise_scale&nbsp;=&nbsp;gauss(0.125,&nbsp;1&nbsp;/&nbsp;48)</div>
<div class="pre"><a id="l151" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l151" class="linenr"> 151</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.contrast&nbsp;=&nbsp;0.5</div>
<div class="pre"><a id="l152" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l152" class="linenr"> 152</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.intensity&nbsp;=&nbsp;0.7</div>
<div class="pre"><a id="l153" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l153" class="linenr"> 153</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l154" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l154" class="linenr"> 154</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tempInt&nbsp;=&nbsp;randint(0,&nbsp;6)</div>
<div class="pre"><a id="l155" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l155" class="linenr"> 155</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texture.distance_metric&nbsp;=&nbsp;metrics[tempInt]</div>
<div class="pre"><a id="l156" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l156" class="linenr"> 156</a> </div>
<div class="pre"><a id="l157" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/randomize_texture.py#l157" class="linenr"> 157</a> &nbsp;&nbsp;&nbsp;&nbsp;return</div>
</div><div class="page_footer">
<div class="page_footer_text">This project founded to maintain a central repository of Blender contrib addons</div>
<a class="rss_logo" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/randomize_texture.py" title="history of add_mesh_rocks/randomize_texture.py RSS feed">RSS</a>
<a class="rss_logo" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/randomize_texture.py" title="history of add_mesh_rocks/randomize_texture.py Atom feed">Atom</a>
</div>
<script type="text/javascript" src="static/gitweb.js"></script>
<script type="text/javascript">
window.onload = function () {
	var tz_cookie = { name: 'gitweb_tz', expires: 14, path: '/' };
	onloadTZSetup('local', tz_cookie, 'datetime');
};
</script>
</body>
</html>