<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<!-- git web interface version 2.23.0, (C) 2005-2006, Kay Sievers <kay.sievers@vrfy.org>, Christian Gierke -->
<!-- git core binaries version 2.23.0 -->
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta name="generator" content="gitweb/2.23.0 git/2.23.0"/>
<meta name="robots" content="index, nofollow"/>
<title>git.blender.org - blender-addons-contrib.git/blob - add_mesh_rocks/settings.py</title>
<base href="https://git.blender.org/gitweb/gitweb.cgi" />
<link rel="stylesheet" type="text/css" href="static/gitweb.css"/>
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/settings.py - RSS feed" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/settings.py" type="application/rss+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/settings.py - RSS feed (no merges)" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/settings.py;opt=--no-merges" type="application/rss+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/settings.py - Atom feed" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/settings.py" type="application/atom+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/settings.py - Atom feed (no merges)" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/settings.py;opt=--no-merges" type="application/atom+xml" />
<link rel="shortcut icon" href="static/git-favicon.png" type="image/png" />
</head>
<body>
<div class="page_header">
<a href="http://git-scm.com/" title="git homepage"><img alt="git" class="logo" height="27" src="static/git-logo.png" width="72" /></a><a href="https://git.blender.org/gitweb/">projects</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git">blender-addons-contrib.git</a> / blob
</div>
<div class="page_nav">
<a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git">summary</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/shortlog">shortlog</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/log">log</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commit/HEAD">commit</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commitdiff/HEAD">commitdiff</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD">tree</a><br/>
<a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/history/HEAD:/add_mesh_rocks/settings.py">history</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob_plain/HEAD:/add_mesh_rocks/settings.py">raw</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py">HEAD</a><br/>
</div>
<div class="header">
<a class="title" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commit/HEAD">Collection Manager: Update Tooltips. Task: T69577</a>
</div>
<div class="page_path"><a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD" title="tree root">[blender-addons-contrib.git]</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD:/add_mesh_rocks" title="add_mesh_rocks">add_mesh_rocks</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob_plain/HEAD:/add_mesh_rocks/settings.py" title="add_mesh_rocks/settings.py">settings.py</a><br/></div>
<div class="page_body">
<div class="pre"><a id="l1" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l1" class="linenr">   1</a> #&nbsp;Paul&nbsp;&quot;BrikBot&quot;&nbsp;Marshall</div>
<div class="pre"><a id="l2" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l2" class="linenr">   2</a> #&nbsp;Created:&nbsp;July&nbsp;1,&nbsp;2011</div>
<div class="pre"><a id="l3" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l3" class="linenr">   3</a> #&nbsp;Last&nbsp;Modified:&nbsp;November&nbsp;17,&nbsp;2011</div>
<div class="pre"><a id="l4" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l4" class="linenr">   4</a> #&nbsp;Homepage&nbsp;(blog):&nbsp;http://post.darkarsenic.com/</div>
<div class="pre"><a id="l5" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l5" class="linenr">   5</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//blog.darkarsenic.com/</div>
<div class="pre"><a id="l6" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l6" class="linenr">   6</a> #&nbsp;Thanks&nbsp;to&nbsp;Meta-Androco,&nbsp;RickyBlender,&nbsp;Ace&nbsp;Dragon,&nbsp;and&nbsp;PKHG&nbsp;for&nbsp;ideas</div>
<div class="pre"><a id="l7" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l7" class="linenr">   7</a> #&nbsp;&nbsp;&nbsp;and&nbsp;testing.</div>
<div class="pre"><a id="l8" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l8" class="linenr">   8</a> #</div>
<div class="pre"><a id="l9" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l9" class="linenr">   9</a> #&nbsp;Coded&nbsp;in&nbsp;IDLE,&nbsp;tested&nbsp;in&nbsp;Blender&nbsp;2.59.&nbsp;&nbsp;NumPy&nbsp;Recommended.</div>
<div class="pre"><a id="l10" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l10" class="linenr">  10</a> #&nbsp;Search&nbsp;for&nbsp;&quot;@todo&quot;&nbsp;to&nbsp;quickly&nbsp;find&nbsp;sections&nbsp;that&nbsp;need&nbsp;work.</div>
<div class="pre"><a id="l11" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l11" class="linenr">  11</a> #</div>
<div class="pre"><a id="l12" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l12" class="linenr">  12</a> #&nbsp;#####&nbsp;BEGIN&nbsp;GPL&nbsp;LICENSE&nbsp;BLOCK&nbsp;#####</div>
<div class="pre"><a id="l13" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l13" class="linenr">  13</a> #</div>
<div class="pre"><a id="l14" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l14" class="linenr">  14</a> #&nbsp;&nbsp;The&nbsp;Blender&nbsp;Rock&nbsp;Creation&nbsp;tool&nbsp;is&nbsp;for&nbsp;rapid&nbsp;generation&nbsp;of</div>
<div class="pre"><a id="l15" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l15" class="linenr">  15</a> #&nbsp;&nbsp;mesh&nbsp;rocks&nbsp;in&nbsp;Blender.</div>
<div class="pre"><a id="l16" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l16" class="linenr">  16</a> #&nbsp;&nbsp;Copyright&nbsp;(C)&nbsp;2011&nbsp;&nbsp;Paul&nbsp;Marshall</div>
<div class="pre"><a id="l17" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l17" class="linenr">  17</a> #</div>
<div class="pre"><a id="l18" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l18" class="linenr">  18</a> #&nbsp;&nbsp;This&nbsp;program&nbsp;is&nbsp;free&nbsp;software:&nbsp;you&nbsp;can&nbsp;redistribute&nbsp;it&nbsp;and/or&nbsp;modify</div>
<div class="pre"><a id="l19" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l19" class="linenr">  19</a> #&nbsp;&nbsp;it&nbsp;under&nbsp;the&nbsp;terms&nbsp;of&nbsp;the&nbsp;GNU&nbsp;General&nbsp;Public&nbsp;License&nbsp;as&nbsp;published&nbsp;by</div>
<div class="pre"><a id="l20" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l20" class="linenr">  20</a> #&nbsp;&nbsp;the&nbsp;Free&nbsp;Software&nbsp;Foundation,&nbsp;either&nbsp;version&nbsp;3&nbsp;of&nbsp;the&nbsp;License,&nbsp;or</div>
<div class="pre"><a id="l21" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l21" class="linenr">  21</a> #&nbsp;&nbsp;(at&nbsp;your&nbsp;option)&nbsp;any&nbsp;later&nbsp;version.</div>
<div class="pre"><a id="l22" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l22" class="linenr">  22</a> #</div>
<div class="pre"><a id="l23" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l23" class="linenr">  23</a> #&nbsp;&nbsp;This&nbsp;program&nbsp;is&nbsp;distributed&nbsp;in&nbsp;the&nbsp;hope&nbsp;that&nbsp;it&nbsp;will&nbsp;be&nbsp;useful,</div>
<div class="pre"><a id="l24" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l24" class="linenr">  24</a> #&nbsp;&nbsp;but&nbsp;WITHOUT&nbsp;ANY&nbsp;WARRANTY;&nbsp;without&nbsp;even&nbsp;the&nbsp;implied&nbsp;warranty&nbsp;of</div>
<div class="pre"><a id="l25" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l25" class="linenr">  25</a> #&nbsp;&nbsp;MERCHANTABILITY&nbsp;or&nbsp;FITNESS&nbsp;FOR&nbsp;A&nbsp;PARTICULAR&nbsp;PURPOSE.&nbsp;&nbsp;See&nbsp;the</div>
<div class="pre"><a id="l26" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l26" class="linenr">  26</a> #&nbsp;&nbsp;GNU&nbsp;General&nbsp;Public&nbsp;License&nbsp;for&nbsp;more&nbsp;details.</div>
<div class="pre"><a id="l27" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l27" class="linenr">  27</a> #</div>
<div class="pre"><a id="l28" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l28" class="linenr">  28</a> #&nbsp;&nbsp;You&nbsp;should&nbsp;have&nbsp;received&nbsp;a&nbsp;copy&nbsp;of&nbsp;the&nbsp;GNU&nbsp;General&nbsp;Public&nbsp;License</div>
<div class="pre"><a id="l29" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l29" class="linenr">  29</a> #&nbsp;&nbsp;along&nbsp;with&nbsp;this&nbsp;program.&nbsp;&nbsp;If&nbsp;not,&nbsp;see&nbsp;&lt;http://www.gnu.org/licenses/&gt;.</div>
<div class="pre"><a id="l30" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l30" class="linenr">  30</a> #</div>
<div class="pre"><a id="l31" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l31" class="linenr">  31</a> #&nbsp;#####&nbsp;END&nbsp;GPL&nbsp;LICENSE&nbsp;BLOCK&nbsp;#####</div>
<div class="pre"><a id="l32" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l32" class="linenr">  32</a> </div>
<div class="pre"><a id="l33" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l33" class="linenr">  33</a> #&nbsp;&lt;pep8&nbsp;compliant&gt;</div>
<div class="pre"><a id="l34" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l34" class="linenr">  34</a> </div>
<div class="pre"><a id="l35" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l35" class="linenr">  35</a> import&nbsp;inspect</div>
<div class="pre"><a id="l36" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l36" class="linenr">  36</a> import&nbsp;shutil</div>
<div class="pre"><a id="l37" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l37" class="linenr">  37</a> from&nbsp;add_mesh_rocks&nbsp;import&nbsp;utils</div>
<div class="pre"><a id="l38" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l38" class="linenr">  38</a> from&nbsp;xml.dom&nbsp;import&nbsp;minidom</div>
<div class="pre"><a id="l39" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l39" class="linenr">  39</a> </div>
<div class="pre"><a id="l40" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l40" class="linenr">  40</a> basePath&nbsp;=&nbsp;inspect.getfile(inspect.currentframe())[0:-len(&quot;settings.py&quot;)]</div>
<div class="pre"><a id="l41" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l41" class="linenr">  41</a> path&nbsp;=&nbsp;basePath&nbsp;+&nbsp;&quot;add_mesh_rocks.xml&quot;</div>
<div class="pre"><a id="l42" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l42" class="linenr">  42</a> </div>
<div class="pre"><a id="l43" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l43" class="linenr">  43</a> try:</div>
<div class="pre"><a id="l44" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l44" class="linenr">  44</a> &nbsp;&nbsp;&nbsp;&nbsp;source&nbsp;=&nbsp;minidom.parse(path)</div>
<div class="pre"><a id="l45" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l45" class="linenr">  45</a> &nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Rock&nbsp;generator&nbsp;settings&nbsp;file&nbsp;found:\n&quot;&nbsp;+&nbsp;path)</div>
<div class="pre"><a id="l46" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l46" class="linenr">  46</a> except:</div>
<div class="pre"><a id="l47" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l47" class="linenr">  47</a> &nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Rock&nbsp;generator&nbsp;settings&nbsp;file&nbsp;not&nbsp;found.&nbsp;&nbsp;Creating&nbsp;settings&nbsp;file.&quot;)</div>
<div class="pre"><a id="l48" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l48" class="linenr">  48</a> &nbsp;&nbsp;&nbsp;&nbsp;shutil.copy(basePath&nbsp;+&nbsp;&quot;factory.xml&quot;,&nbsp;path)</div>
<div class="pre"><a id="l49" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l49" class="linenr">  49</a> &nbsp;&nbsp;&nbsp;&nbsp;source&nbsp;=&nbsp;minidom.parse(path)</div>
<div class="pre"><a id="l50" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l50" class="linenr">  50</a> </div>
<div class="pre"><a id="l51" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l51" class="linenr">  51</a> xmlDefault&nbsp;=&nbsp;source.getElementsByTagName(&#39;default&#39;)[0]</div>
<div class="pre"><a id="l52" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l52" class="linenr">  52</a> xmlPresets&nbsp;=&nbsp;source.getElementsByTagName(&#39;preset&#39;)</div>
<div class="pre"><a id="l53" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l53" class="linenr">  53</a> default&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l54" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l54" class="linenr">  54</a> presets&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l55" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l55" class="linenr">  55</a> </div>
<div class="pre"><a id="l56" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l56" class="linenr">  56</a> #&nbsp;-----&nbsp;Gets&nbsp;and&nbsp;Sets&nbsp;-----#</div>
<div class="pre"><a id="l57" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l57" class="linenr">  57</a> </div>
<div class="pre"><a id="l58" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l58" class="linenr">  58</a> </div>
<div class="pre"><a id="l59" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l59" class="linenr">  59</a> def&nbsp;getDefault():</div>
<div class="pre"><a id="l60" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l60" class="linenr">  60</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;default</div>
<div class="pre"><a id="l61" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l61" class="linenr">  61</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;default</div>
<div class="pre"><a id="l62" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l62" class="linenr">  62</a> </div>
<div class="pre"><a id="l63" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l63" class="linenr">  63</a> </div>
<div class="pre"><a id="l64" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l64" class="linenr">  64</a> def&nbsp;getPresetLists():</div>
<div class="pre"><a id="l65" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l65" class="linenr">  65</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;presets</div>
<div class="pre"><a id="l66" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l66" class="linenr">  66</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;presets</div>
<div class="pre"><a id="l67" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l67" class="linenr">  67</a> </div>
<div class="pre"><a id="l68" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l68" class="linenr">  68</a> </div>
<div class="pre"><a id="l69" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l69" class="linenr">  69</a> def&nbsp;getPreset(ID=0):</div>
<div class="pre"><a id="l70" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l70" class="linenr">  70</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;presets</div>
<div class="pre"><a id="l71" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l71" class="linenr">  71</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;presets[ID]</div>
<div class="pre"><a id="l72" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l72" class="linenr">  72</a> </div>
<div class="pre"><a id="l73" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l73" class="linenr">  73</a> #&nbsp;----------&nbsp;Core&nbsp;----------#</div>
<div class="pre"><a id="l74" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l74" class="linenr">  74</a> </div>
<div class="pre"><a id="l75" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l75" class="linenr">  75</a> </div>
<div class="pre"><a id="l76" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l76" class="linenr">  76</a> def&nbsp;parse():</div>
<div class="pre"><a id="l77" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l77" class="linenr">  77</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;xmlDefault</div>
<div class="pre"><a id="l78" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l78" class="linenr">  78</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;xmlPresets</div>
<div class="pre"><a id="l79" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l79" class="linenr">  79</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;default</div>
<div class="pre"><a id="l80" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l80" class="linenr">  80</a> &nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;presets</div>
<div class="pre"><a id="l81" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l81" class="linenr">  81</a> </div>
<div class="pre"><a id="l82" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l82" class="linenr">  82</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Parse&nbsp;default&nbsp;values</div>
<div class="pre"><a id="l83" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l83" class="linenr">  83</a> &nbsp;&nbsp;&nbsp;&nbsp;default&nbsp;=&nbsp;parseNode(xmlDefault)</div>
<div class="pre"><a id="l84" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l84" class="linenr">  84</a> </div>
<div class="pre"><a id="l85" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l85" class="linenr">  85</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Parse&nbsp;preset&nbsp;values</div>
<div class="pre"><a id="l86" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l86" class="linenr">  86</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;setting&nbsp;in&nbsp;xmlPresets:</div>
<div class="pre"><a id="l87" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l87" class="linenr">  87</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;presets.append(parseNode(setting))</div>
<div class="pre"><a id="l88" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l88" class="linenr">  88</a> </div>
<div class="pre"><a id="l89" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l89" class="linenr">  89</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&#39;{FINISHED}&#39;</div>
<div class="pre"><a id="l90" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l90" class="linenr">  90</a> </div>
<div class="pre"><a id="l91" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l91" class="linenr">  91</a> </div>
<div class="pre"><a id="l92" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l92" class="linenr">  92</a> #&nbsp;Takes&nbsp;a&nbsp;node&nbsp;and&nbsp;parses&nbsp;it&nbsp;for&nbsp;data.&nbsp;&nbsp;Relies&nbsp;on&nbsp;that&nbsp;setting.xml&nbsp;has</div>
<div class="pre"><a id="l93" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l93" class="linenr">  93</a> #&nbsp;&nbsp;&nbsp;a&nbsp;valid&nbsp;format&nbsp;as&nbsp;specified&nbsp;by&nbsp;the&nbsp;DTD.</div>
<div class="pre"><a id="l94" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l94" class="linenr">  94</a> #&nbsp;For&nbsp;some&nbsp;reason&nbsp;minidom&nbsp;places&nbsp;an&nbsp;empty&nbsp;child&nbsp;node&nbsp;for&nbsp;every&nbsp;other&nbsp;node.</div>
<div class="pre"><a id="l95" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l95" class="linenr">  95</a> def&nbsp;parseNode(setting,&nbsp;title=True):</div>
<div class="pre"><a id="l96" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l96" class="linenr">  96</a> &nbsp;&nbsp;&nbsp;&nbsp;loc&nbsp;=&nbsp;1</div>
<div class="pre"><a id="l97" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l97" class="linenr">  97</a> </div>
<div class="pre"><a id="l98" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l98" class="linenr">  98</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;title:</div>
<div class="pre"><a id="l99" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l99" class="linenr">  99</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Preset&nbsp;name&nbsp;(xmlPreset.childNodes[1]):</div>
<div class="pre"><a id="l100" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l100" class="linenr"> 100</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title&nbsp;=&nbsp;setting.childNodes[loc].childNodes[0].data</div>
<div class="pre"><a id="l101" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l101" class="linenr"> 101</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loc&nbsp;+=&nbsp;2</div>
<div class="pre"><a id="l102" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l102" class="linenr"> 102</a> </div>
<div class="pre"><a id="l103" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l103" class="linenr"> 103</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Preset&nbsp;size&nbsp;values&nbsp;(xmlPreset.childNodes[3]):</div>
<div class="pre"><a id="l104" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l104" class="linenr"> 104</a> &nbsp;&nbsp;&nbsp;&nbsp;scaleX&nbsp;=&nbsp;[float(setting.childNodes[loc].childNodes[1].childNodes[3].childNodes[0].data),</div>
<div class="pre"><a id="l105" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l105" class="linenr"> 105</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;float(setting.childNodes[loc].childNodes[1].childNodes[5].childNodes[0].data)]</div>
<div class="pre"><a id="l106" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l106" class="linenr"> 106</a> &nbsp;&nbsp;&nbsp;&nbsp;scaleY&nbsp;=&nbsp;[float(setting.childNodes[loc].childNodes[3].childNodes[3].childNodes[0].data),</div>
<div class="pre"><a id="l107" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l107" class="linenr"> 107</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;float(setting.childNodes[loc].childNodes[3].childNodes[5].childNodes[0].data)]</div>
<div class="pre"><a id="l108" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l108" class="linenr"> 108</a> &nbsp;&nbsp;&nbsp;&nbsp;scaleZ&nbsp;=&nbsp;[float(setting.childNodes[loc].childNodes[5].childNodes[3].childNodes[0].data),</div>
<div class="pre"><a id="l109" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l109" class="linenr"> 109</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;float(setting.childNodes[loc].childNodes[5].childNodes[5].childNodes[0].data)]</div>
<div class="pre"><a id="l110" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l110" class="linenr"> 110</a> &nbsp;&nbsp;&nbsp;&nbsp;skewX&nbsp;=&nbsp;float(setting.childNodes[loc].childNodes[7].childNodes[3].childNodes[0].data)</div>
<div class="pre"><a id="l111" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l111" class="linenr"> 111</a> &nbsp;&nbsp;&nbsp;&nbsp;skewY&nbsp;=&nbsp;float(setting.childNodes[loc].childNodes[9].childNodes[3].childNodes[0].data)</div>
<div class="pre"><a id="l112" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l112" class="linenr"> 112</a> &nbsp;&nbsp;&nbsp;&nbsp;skewZ&nbsp;=&nbsp;float(setting.childNodes[loc].childNodes[11].childNodes[3].childNodes[0].data)</div>
<div class="pre"><a id="l113" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l113" class="linenr"> 113</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;setting.childNodes[loc].childNodes[13].childNodes[0].data&nbsp;==&nbsp;&#39;False&#39;:</div>
<div class="pre"><a id="l114" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l114" class="linenr"> 114</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_scale_dis&nbsp;=&nbsp;False</div>
<div class="pre"><a id="l115" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l115" class="linenr"> 115</a> &nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l116" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l116" class="linenr"> 116</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_scale_dis&nbsp;=&nbsp;True</div>
<div class="pre"><a id="l117" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l117" class="linenr"> 117</a> &nbsp;&nbsp;&nbsp;&nbsp;scale_fac&nbsp;=&nbsp;utils.toList(setting.childNodes[loc].childNodes[15].childNodes[0].data)</div>
<div class="pre"><a id="l118" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l118" class="linenr"> 118</a> &nbsp;&nbsp;&nbsp;&nbsp;loc&nbsp;+=&nbsp;2</div>
<div class="pre"><a id="l119" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l119" class="linenr"> 119</a> </div>
<div class="pre"><a id="l120" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l120" class="linenr"> 120</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Presst&nbsp;shape&nbsp;values&nbsp;(xmlPreset.childNodes[5]):</div>
<div class="pre"><a id="l121" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l121" class="linenr"> 121</a> &nbsp;&nbsp;&nbsp;&nbsp;deform&nbsp;=&nbsp;float(setting.childNodes[loc].childNodes[1].childNodes[0].data)</div>
<div class="pre"><a id="l122" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l122" class="linenr"> 122</a> &nbsp;&nbsp;&nbsp;&nbsp;rough&nbsp;=&nbsp;float(setting.childNodes[loc].childNodes[3].childNodes[0].data)</div>
<div class="pre"><a id="l123" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l123" class="linenr"> 123</a> &nbsp;&nbsp;&nbsp;&nbsp;detail&nbsp;=&nbsp;int(setting.childNodes[loc].childNodes[5].childNodes[0].data)</div>
<div class="pre"><a id="l124" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l124" class="linenr"> 124</a> &nbsp;&nbsp;&nbsp;&nbsp;display_detail&nbsp;=&nbsp;int(setting.childNodes[loc].childNodes[7].childNodes[0].data)</div>
<div class="pre"><a id="l125" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l125" class="linenr"> 125</a> &nbsp;&nbsp;&nbsp;&nbsp;smooth_fac&nbsp;=&nbsp;float(setting.childNodes[loc].childNodes[9].childNodes[0].data)</div>
<div class="pre"><a id="l126" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l126" class="linenr"> 126</a> &nbsp;&nbsp;&nbsp;&nbsp;smooth_it&nbsp;=&nbsp;int(setting.childNodes[loc].childNodes[11].childNodes[0].data)</div>
<div class="pre"><a id="l127" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l127" class="linenr"> 127</a> &nbsp;&nbsp;&nbsp;&nbsp;loc&nbsp;+=&nbsp;2</div>
<div class="pre"><a id="l128" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l128" class="linenr"> 128</a> </div>
<div class="pre"><a id="l129" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l129" class="linenr"> 129</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Preset&nbsp;material&nbsp;values&nbsp;(xmlPreset.childNodes[7]):</div>
<div class="pre"><a id="l130" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l130" class="linenr"> 130</a> &nbsp;&nbsp;&nbsp;&nbsp;loc&nbsp;+=&nbsp;2</div>
<div class="pre"><a id="l131" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l131" class="linenr"> 131</a> </div>
<div class="pre"><a id="l132" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l132" class="linenr"> 132</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Preset&nbsp;random&nbsp;values&nbsp;(xmlPreset.childNodes[9]):</div>
<div class="pre"><a id="l133" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l133" class="linenr"> 133</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;setting.childNodes[loc].childNodes[1].childNodes[0].data&nbsp;==&nbsp;&#39;True&#39;:</div>
<div class="pre"><a id="l134" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l134" class="linenr"> 134</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_generate&nbsp;=&nbsp;True</div>
<div class="pre"><a id="l135" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l135" class="linenr"> 135</a> &nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l136" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l136" class="linenr"> 136</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_generate&nbsp;=&nbsp;False</div>
<div class="pre"><a id="l137" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l137" class="linenr"> 137</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;setting.childNodes[loc].childNodes[3].childNodes[0].data&nbsp;==&nbsp;&#39;False&#39;:</div>
<div class="pre"><a id="l138" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l138" class="linenr"> 138</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_random_seed&nbsp;=&nbsp;False</div>
<div class="pre"><a id="l139" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l139" class="linenr"> 139</a> &nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l140" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l140" class="linenr"> 140</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_random_seed&nbsp;=&nbsp;True</div>
<div class="pre"><a id="l141" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l141" class="linenr"> 141</a> &nbsp;&nbsp;&nbsp;&nbsp;user_seed&nbsp;=&nbsp;int(setting.childNodes[loc].childNodes[5].childNodes[0].data)</div>
<div class="pre"><a id="l142" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l142" class="linenr"> 142</a> </div>
<div class="pre"><a id="l143" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l143" class="linenr"> 143</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;title:</div>
<div class="pre"><a id="l144" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l144" class="linenr"> 144</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parsed&nbsp;=&nbsp;[title,&nbsp;scaleX,&nbsp;scaleY,&nbsp;scaleZ,&nbsp;skewX,&nbsp;skewY,&nbsp;skewZ,</div>
<div class="pre"><a id="l145" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l145" class="linenr"> 145</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_scale_dis,&nbsp;scale_fac,&nbsp;deform,&nbsp;rough,&nbsp;detail,</div>
<div class="pre"><a id="l146" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l146" class="linenr"> 146</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;display_detail,&nbsp;smooth_fac,&nbsp;smooth_it,</div>
<div class="pre"><a id="l147" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l147" class="linenr"> 147</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_generate,&nbsp;use_random_seed,&nbsp;user_seed]</div>
<div class="pre"><a id="l148" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l148" class="linenr"> 148</a> &nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l149" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l149" class="linenr"> 149</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parsed&nbsp;=&nbsp;[scaleX,&nbsp;scaleY,&nbsp;scaleZ,&nbsp;skewX,&nbsp;skewY,&nbsp;skewZ,&nbsp;use_scale_dis,</div>
<div class="pre"><a id="l150" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l150" class="linenr"> 150</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scale_fac,&nbsp;deform,&nbsp;rough,&nbsp;detail,&nbsp;display_detail,&nbsp;smooth_fac,</div>
<div class="pre"><a id="l151" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l151" class="linenr"> 151</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;smooth_it,&nbsp;use_generate,&nbsp;use_random_seed,&nbsp;user_seed]</div>
<div class="pre"><a id="l152" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l152" class="linenr"> 152</a> </div>
<div class="pre"><a id="l153" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l153" class="linenr"> 153</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;parsed</div>
<div class="pre"><a id="l154" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l154" class="linenr"> 154</a> </div>
<div class="pre"><a id="l155" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l155" class="linenr"> 155</a> </div>
<div class="pre"><a id="l156" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l156" class="linenr"> 156</a> def&nbsp;save():</div>
<div class="pre"><a id="l157" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l157" class="linenr"> 157</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&#39;{FINISHED}&#39;</div>
<div class="pre"><a id="l158" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l158" class="linenr"> 158</a> </div>
<div class="pre"><a id="l159" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l159" class="linenr"> 159</a> </div>
<div class="pre"><a id="l160" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l160" class="linenr"> 160</a> def&nbsp;_print():</div>
<div class="pre"><a id="l161" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l161" class="linenr"> 161</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;presets:</div>
<div class="pre"><a id="l162" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l162" class="linenr"> 162</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(i)</div>
<div class="pre"><a id="l163" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/settings.py#l163" class="linenr"> 163</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&#39;{FINISHED}&#39;</div>
</div><div class="page_footer">
<div class="page_footer_text">This project founded to maintain a central repository of Blender contrib addons</div>
<a class="rss_logo" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/settings.py" title="history of add_mesh_rocks/settings.py RSS feed">RSS</a>
<a class="rss_logo" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/settings.py" title="history of add_mesh_rocks/settings.py Atom feed">Atom</a>
</div>
<script type="text/javascript" src="static/gitweb.js"></script>
<script type="text/javascript">
window.onload = function () {
	var tz_cookie = { name: 'gitweb_tz', expires: 14, path: '/' };
	onloadTZSetup('local', tz_cookie, 'datetime');
};
</script>
</body>
</html>