<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<!-- git web interface version 2.23.0, (C) 2005-2006, Kay Sievers <kay.sievers@vrfy.org>, Christian Gierke -->
<!-- git core binaries version 2.23.0 -->
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta name="generator" content="gitweb/2.23.0 git/2.23.0"/>
<meta name="robots" content="index, nofollow"/>
<title>git.blender.org - blender-addons-contrib.git/blob - add_mesh_rocks/utils.py</title>
<base href="https://git.blender.org/gitweb/gitweb.cgi" />
<link rel="stylesheet" type="text/css" href="static/gitweb.css"/>
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/utils.py - RSS feed" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/utils.py" type="application/rss+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/utils.py - RSS feed (no merges)" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/utils.py;opt=--no-merges" type="application/rss+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/utils.py - Atom feed" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/utils.py" type="application/atom+xml" />
<link rel="alternate" title="blender-addons-contrib.git - history of add_mesh_rocks/utils.py - Atom feed (no merges)" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/utils.py;opt=--no-merges" type="application/atom+xml" />
<link rel="shortcut icon" href="static/git-favicon.png" type="image/png" />
</head>
<body>
<div class="page_header">
<a href="http://git-scm.com/" title="git homepage"><img alt="git" class="logo" height="27" src="static/git-logo.png" width="72" /></a><a href="https://git.blender.org/gitweb/">projects</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git">blender-addons-contrib.git</a> / blob
</div>
<div class="page_nav">
<a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git">summary</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/shortlog">shortlog</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/log">log</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commit/HEAD">commit</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commitdiff/HEAD">commitdiff</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD">tree</a><br/>
<a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/history/HEAD:/add_mesh_rocks/utils.py">history</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob_plain/HEAD:/add_mesh_rocks/utils.py">raw</a> | <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py">HEAD</a><br/>
</div>
<div class="header">
<a class="title" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/commit/HEAD">Collection Manager: Update Tooltips. Task: T69577</a>
</div>
<div class="page_path"><a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD" title="tree root">[blender-addons-contrib.git]</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/tree/HEAD:/add_mesh_rocks" title="add_mesh_rocks">add_mesh_rocks</a> / <a href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob_plain/HEAD:/add_mesh_rocks/utils.py" title="add_mesh_rocks/utils.py">utils.py</a><br/></div>
<div class="page_body">
<div class="pre"><a id="l1" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l1" class="linenr">   1</a> #&nbsp;#####&nbsp;BEGIN&nbsp;GPL&nbsp;LICENSE&nbsp;BLOCK&nbsp;#####</div>
<div class="pre"><a id="l2" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l2" class="linenr">   2</a> #</div>
<div class="pre"><a id="l3" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l3" class="linenr">   3</a> #&nbsp;&nbsp;The&nbsp;Blender&nbsp;Rock&nbsp;Creation&nbsp;tool&nbsp;is&nbsp;for&nbsp;rapid&nbsp;generation&nbsp;of&nbsp;mesh&nbsp;rocks.</div>
<div class="pre"><a id="l4" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l4" class="linenr">   4</a> #&nbsp;&nbsp;Copyright&nbsp;(C)&nbsp;2011&nbsp;&nbsp;Paul&nbsp;Marshall</div>
<div class="pre"><a id="l5" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l5" class="linenr">   5</a> #</div>
<div class="pre"><a id="l6" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l6" class="linenr">   6</a> #&nbsp;&nbsp;This&nbsp;program&nbsp;is&nbsp;free&nbsp;software:&nbsp;you&nbsp;can&nbsp;redistribute&nbsp;it&nbsp;and/or&nbsp;modify</div>
<div class="pre"><a id="l7" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l7" class="linenr">   7</a> #&nbsp;&nbsp;it&nbsp;under&nbsp;the&nbsp;terms&nbsp;of&nbsp;the&nbsp;GNU&nbsp;General&nbsp;Public&nbsp;License&nbsp;as&nbsp;published&nbsp;by</div>
<div class="pre"><a id="l8" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l8" class="linenr">   8</a> #&nbsp;&nbsp;the&nbsp;Free&nbsp;Software&nbsp;Foundation,&nbsp;either&nbsp;version&nbsp;3&nbsp;of&nbsp;the&nbsp;License,&nbsp;or</div>
<div class="pre"><a id="l9" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l9" class="linenr">   9</a> #&nbsp;&nbsp;(at&nbsp;your&nbsp;option)&nbsp;any&nbsp;later&nbsp;version.</div>
<div class="pre"><a id="l10" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l10" class="linenr">  10</a> #</div>
<div class="pre"><a id="l11" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l11" class="linenr">  11</a> #&nbsp;&nbsp;This&nbsp;program&nbsp;is&nbsp;distributed&nbsp;in&nbsp;the&nbsp;hope&nbsp;that&nbsp;it&nbsp;will&nbsp;be&nbsp;useful,</div>
<div class="pre"><a id="l12" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l12" class="linenr">  12</a> #&nbsp;&nbsp;but&nbsp;WITHOUT&nbsp;ANY&nbsp;WARRANTY;&nbsp;without&nbsp;even&nbsp;the&nbsp;implied&nbsp;warranty&nbsp;of</div>
<div class="pre"><a id="l13" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l13" class="linenr">  13</a> #&nbsp;&nbsp;MERCHANTABILITY&nbsp;or&nbsp;FITNESS&nbsp;FOR&nbsp;A&nbsp;PARTICULAR&nbsp;PURPOSE.&nbsp;&nbsp;See&nbsp;the</div>
<div class="pre"><a id="l14" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l14" class="linenr">  14</a> #&nbsp;&nbsp;GNU&nbsp;General&nbsp;Public&nbsp;License&nbsp;for&nbsp;more&nbsp;details.</div>
<div class="pre"><a id="l15" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l15" class="linenr">  15</a> #</div>
<div class="pre"><a id="l16" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l16" class="linenr">  16</a> #&nbsp;&nbsp;You&nbsp;should&nbsp;have&nbsp;received&nbsp;a&nbsp;copy&nbsp;of&nbsp;the&nbsp;GNU&nbsp;General&nbsp;Public&nbsp;License</div>
<div class="pre"><a id="l17" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l17" class="linenr">  17</a> #&nbsp;&nbsp;along&nbsp;with&nbsp;this&nbsp;program.&nbsp;&nbsp;If&nbsp;not,&nbsp;see&nbsp;&lt;http://www.gnu.org/licenses/&gt;.</div>
<div class="pre"><a id="l18" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l18" class="linenr">  18</a> #</div>
<div class="pre"><a id="l19" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l19" class="linenr">  19</a> #&nbsp;#####&nbsp;END&nbsp;GPL&nbsp;LICENSE&nbsp;BLOCK&nbsp;#####</div>
<div class="pre"><a id="l20" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l20" class="linenr">  20</a> </div>
<div class="pre"><a id="l21" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l21" class="linenr">  21</a> #&nbsp;&lt;pep8&nbsp;compliant&gt;</div>
<div class="pre"><a id="l22" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l22" class="linenr">  22</a> </div>
<div class="pre"><a id="l23" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l23" class="linenr">  23</a> </div>
<div class="pre"><a id="l24" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l24" class="linenr">  24</a> #&nbsp;Converts&nbsp;a&nbsp;formated&nbsp;string&nbsp;to&nbsp;a&nbsp;float&nbsp;tuple:</div>
<div class="pre"><a id="l25" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l25" class="linenr">  25</a> #&nbsp;&nbsp;&nbsp;IN&nbsp;-&nbsp;&#39;(0.5,&nbsp;0.2)&#39;&nbsp;-&gt;&nbsp;CONVERT&nbsp;-&gt;&nbsp;OUT&nbsp;-&nbsp;(0.5,&nbsp;0.2)</div>
<div class="pre"><a id="l26" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l26" class="linenr">  26</a> def&nbsp;toTuple(stringIn):</div>
<div class="pre"><a id="l27" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l27" class="linenr">  27</a> &nbsp;&nbsp;&nbsp;&nbsp;sTemp&nbsp;=&nbsp;str(stringIn)[1:len(str(stringIn))&nbsp;-&nbsp;1].split(&#39;,&nbsp;&#39;)</div>
<div class="pre"><a id="l28" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l28" class="linenr">  28</a> &nbsp;&nbsp;&nbsp;&nbsp;fTemp&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l29" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l29" class="linenr">  29</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;sTemp:</div>
<div class="pre"><a id="l30" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l30" class="linenr">  30</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fTemp.append(float(i))</div>
<div class="pre"><a id="l31" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l31" class="linenr">  31</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tuple(fTemp)</div>
<div class="pre"><a id="l32" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l32" class="linenr">  32</a> </div>
<div class="pre"><a id="l33" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l33" class="linenr">  33</a> </div>
<div class="pre"><a id="l34" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l34" class="linenr">  34</a> #&nbsp;Converts&nbsp;a&nbsp;formated&nbsp;string&nbsp;to&nbsp;a&nbsp;float&nbsp;tuple:</div>
<div class="pre"><a id="l35" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l35" class="linenr">  35</a> #&nbsp;&nbsp;&nbsp;IN&nbsp;-&nbsp;&#39;[0.5,&nbsp;0.2]&#39;&nbsp;-&gt;&nbsp;CONVERT&nbsp;-&gt;&nbsp;OUT&nbsp;-&nbsp;[0.5,&nbsp;0.2]</div>
<div class="pre"><a id="l36" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l36" class="linenr">  36</a> def&nbsp;toList(stringIn):</div>
<div class="pre"><a id="l37" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l37" class="linenr">  37</a> &nbsp;&nbsp;&nbsp;&nbsp;sTemp&nbsp;=&nbsp;str(stringIn)[1:len(str(stringIn))&nbsp;-&nbsp;1].split(&#39;,&nbsp;&#39;)</div>
<div class="pre"><a id="l38" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l38" class="linenr">  38</a> &nbsp;&nbsp;&nbsp;&nbsp;fTemp&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l39" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l39" class="linenr">  39</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;sTemp:</div>
<div class="pre"><a id="l40" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l40" class="linenr">  40</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fTemp.append(float(i))</div>
<div class="pre"><a id="l41" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l41" class="linenr">  41</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;fTemp</div>
<div class="pre"><a id="l42" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l42" class="linenr">  42</a> </div>
<div class="pre"><a id="l43" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l43" class="linenr">  43</a> </div>
<div class="pre"><a id="l44" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l44" class="linenr">  44</a> #&nbsp;Converts&nbsp;each&nbsp;item&nbsp;of&nbsp;a&nbsp;list&nbsp;into&nbsp;a&nbsp;float:</div>
<div class="pre"><a id="l45" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l45" class="linenr">  45</a> def&nbsp;toFloats(inList):</div>
<div class="pre"><a id="l46" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l46" class="linenr">  46</a> &nbsp;&nbsp;&nbsp;&nbsp;outList&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l47" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l47" class="linenr">  47</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;inList:</div>
<div class="pre"><a id="l48" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l48" class="linenr">  48</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;outList.append(float(i))</div>
<div class="pre"><a id="l49" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l49" class="linenr">  49</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;outList</div>
<div class="pre"><a id="l50" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l50" class="linenr">  50</a> </div>
<div class="pre"><a id="l51" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l51" class="linenr">  51</a> </div>
<div class="pre"><a id="l52" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l52" class="linenr">  52</a> #&nbsp;Converts&nbsp;each&nbsp;item&nbsp;of&nbsp;a&nbsp;list&nbsp;into&nbsp;an&nbsp;integer:</div>
<div class="pre"><a id="l53" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l53" class="linenr">  53</a> def&nbsp;toInts(inList):</div>
<div class="pre"><a id="l54" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l54" class="linenr">  54</a> &nbsp;&nbsp;&nbsp;&nbsp;outList&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l55" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l55" class="linenr">  55</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;inList:</div>
<div class="pre"><a id="l56" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l56" class="linenr">  56</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;outList.append(int(i))</div>
<div class="pre"><a id="l57" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l57" class="linenr">  57</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;outList</div>
<div class="pre"><a id="l58" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l58" class="linenr">  58</a> </div>
<div class="pre"><a id="l59" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l59" class="linenr">  59</a> </div>
<div class="pre"><a id="l60" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l60" class="linenr">  60</a> #&nbsp;Sets&nbsp;all&nbsp;faces&nbsp;smooth.&nbsp;&nbsp;Done&nbsp;this&nbsp;way&nbsp;since&nbsp;I&nbsp;can&#39;t</div>
<div class="pre"><a id="l61" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l61" class="linenr">  61</a> #&nbsp;find&nbsp;a&nbsp;simple&nbsp;way&nbsp;without&nbsp;using&nbsp;bpy.ops:</div>
<div class="pre"><a id="l62" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l62" class="linenr">  62</a> def&nbsp;smooth(mesh):</div>
<div class="pre"><a id="l63" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l63" class="linenr">  63</a> &nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;bmesh</div>
<div class="pre"><a id="l64" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l64" class="linenr">  64</a> &nbsp;&nbsp;&nbsp;&nbsp;bm&nbsp;=&nbsp;bmesh.new()</div>
<div class="pre"><a id="l65" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l65" class="linenr">  65</a> &nbsp;&nbsp;&nbsp;&nbsp;bm.from_mesh(mesh)</div>
<div class="pre"><a id="l66" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l66" class="linenr">  66</a> &nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;f&nbsp;in&nbsp;bm.faces:</div>
<div class="pre"><a id="l67" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l67" class="linenr">  67</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f.smooth&nbsp;=&nbsp;True</div>
<div class="pre"><a id="l68" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l68" class="linenr">  68</a> &nbsp;&nbsp;&nbsp;&nbsp;bm.to_mesh(mesh)</div>
<div class="pre"><a id="l69" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l69" class="linenr">  69</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mesh</div>
<div class="pre"><a id="l70" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l70" class="linenr">  70</a> </div>
<div class="pre"><a id="l71" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l71" class="linenr">  71</a> </div>
<div class="pre"><a id="l72" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l72" class="linenr">  72</a> #&nbsp;This&nbsp;try&nbsp;block&nbsp;allows&nbsp;for&nbsp;the&nbsp;script&nbsp;to&nbsp;psudo-intelligently&nbsp;select&nbsp;the</div>
<div class="pre"><a id="l73" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l73" class="linenr">  73</a> #&nbsp;appropriate&nbsp;random&nbsp;to&nbsp;use.&nbsp;&nbsp;If&nbsp;Numpy&#39;s&nbsp;random&nbsp;is&nbsp;present&nbsp;it&nbsp;will&nbsp;use&nbsp;that.</div>
<div class="pre"><a id="l74" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l74" class="linenr">  74</a> #&nbsp;If&nbsp;Numpy&#39;s&nbsp;random&nbsp;is&nbsp;not&nbsp;present,&nbsp;it&nbsp;will&nbsp;through&nbsp;a&nbsp;&quot;module&nbsp;not&nbsp;found&quot;</div>
<div class="pre"><a id="l75" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l75" class="linenr">  75</a> #&nbsp;exception&nbsp;and&nbsp;instead&nbsp;use&nbsp;the&nbsp;slower&nbsp;built-in&nbsp;random&nbsp;that&nbsp;Python&nbsp;has.</div>
<div class="pre"><a id="l76" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l76" class="linenr">  76</a> try:</div>
<div class="pre"><a id="l77" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l77" class="linenr">  77</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;from&nbsp;numpy.random&nbsp;import&nbsp;random_integers&nbsp;as&nbsp;randint</div>
<div class="pre"><a id="l78" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l78" class="linenr">  78</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;numpy.random&nbsp;import&nbsp;normal&nbsp;as&nbsp;gauss</div>
<div class="pre"><a id="l79" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l79" class="linenr">  79</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;from&nbsp;numpy.random&nbsp;import&nbsp;(beta,</div>
<div class="pre"><a id="l80" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l80" class="linenr">  80</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;uniform,</div>
<div class="pre"><a id="l81" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l81" class="linenr">  81</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;seed,</div>
<div class="pre"><a id="l82" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l82" class="linenr">  82</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;weibull)</div>
<div class="pre"><a id="l83" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l83" class="linenr">  83</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;print(&quot;Rock&nbsp;Generator:&nbsp;Numpy&nbsp;found.&quot;)</div>
<div class="pre"><a id="l84" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l84" class="linenr">  84</a> &nbsp;&nbsp;&nbsp;&nbsp;numpy&nbsp;=&nbsp;True</div>
<div class="pre"><a id="l85" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l85" class="linenr">  85</a> except:</div>
<div class="pre"><a id="l86" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l86" class="linenr">  86</a> &nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;random&nbsp;import&nbsp;(</div>
<div class="pre"><a id="l87" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l87" class="linenr">  87</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;randint,</div>
<div class="pre"><a id="l88" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l88" class="linenr">  88</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gauss,</div>
<div class="pre"><a id="l89" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l89" class="linenr">  89</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;uniform,</div>
<div class="pre"><a id="l90" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l90" class="linenr">  90</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;seed</div>
<div class="pre"><a id="l91" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l91" class="linenr">  91</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)</div>
<div class="pre"><a id="l92" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l92" class="linenr">  92</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;from&nbsp;random&nbsp;import&nbsp;betavariate&nbsp;as&nbsp;beta</div>
<div class="pre"><a id="l93" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l93" class="linenr">  93</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;from&nbsp;random&nbsp;import&nbsp;weibullvariate&nbsp;as&nbsp;weibull</div>
<div class="pre"><a id="l94" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l94" class="linenr">  94</a> &nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Rock&nbsp;Generator:&nbsp;Numpy&nbsp;not&nbsp;found.&nbsp;&nbsp;Using&nbsp;Python&#39;s&nbsp;random.&quot;)</div>
<div class="pre"><a id="l95" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l95" class="linenr">  95</a> &nbsp;&nbsp;&nbsp;&nbsp;numpy&nbsp;=&nbsp;False</div>
<div class="pre"><a id="l96" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l96" class="linenr">  96</a> #&nbsp;Artifically&nbsp;skews&nbsp;a&nbsp;normal&nbsp;(gaussian)&nbsp;distribution.&nbsp;&nbsp;This&nbsp;will&nbsp;not&nbsp;create</div>
<div class="pre"><a id="l97" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l97" class="linenr">  97</a> #&nbsp;a&nbsp;continuous&nbsp;distribution&nbsp;curve&nbsp;but&nbsp;instead&nbsp;acts&nbsp;as&nbsp;a&nbsp;piecewise&nbsp;finction.</div>
<div class="pre"><a id="l98" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l98" class="linenr">  98</a> #&nbsp;This&nbsp;linearly&nbsp;scales&nbsp;the&nbsp;output&nbsp;on&nbsp;one&nbsp;side&nbsp;to&nbsp;fit&nbsp;the&nbsp;bounds.</div>
<div class="pre"><a id="l99" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l99" class="linenr">  99</a> #</div>
<div class="pre"><a id="l100" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l100" class="linenr"> 100</a> #&nbsp;Example&nbsp;output&nbsp;historgrams:</div>
<div class="pre"><a id="l101" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l101" class="linenr"> 101</a> #</div>
<div class="pre"><a id="l102" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l102" class="linenr"> 102</a> #&nbsp;Upper&nbsp;skewed:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lower&nbsp;skewed:</div>
<div class="pre"><a id="l103" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l103" class="linenr"> 103</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▄&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_</div>
<div class="pre"><a id="l104" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l104" class="linenr"> 104</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;█&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;█</div>
<div class="pre"><a id="l105" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l105" class="linenr"> 105</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;█_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;█</div>
<div class="pre"><a id="l106" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l106" class="linenr"> 106</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;██&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_█</div>
<div class="pre"><a id="l107" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l107" class="linenr"> 107</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_██&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;██</div>
<div class="pre"><a id="l108" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l108" class="linenr"> 108</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_▄███_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;██&nbsp;_</div>
<div class="pre"><a id="l109" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l109" class="linenr"> 109</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▄██████&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;▄██▄█▄_</div>
<div class="pre"><a id="l110" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l110" class="linenr"> 110</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_█▄███████&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;███████</div>
<div class="pre"><a id="l111" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l111" class="linenr"> 111</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_██████████_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;████████▄▄█_&nbsp;_</div>
<div class="pre"><a id="l112" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l112" class="linenr"> 112</a> #&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_▄▄████████████&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;████████████▄█_</div>
<div class="pre"><a id="l113" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l113" class="linenr"> 113</a> #&nbsp;&nbsp;|&nbsp;_▄_&nbsp;▄███████████████▄_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;_▄███████████████▄▄_</div>
<div class="pre"><a id="l114" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l114" class="linenr"> 114</a> #&nbsp;&nbsp;&nbsp;-------------------------&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-----------------------</div>
<div class="pre"><a id="l115" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l115" class="linenr"> 115</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|mu&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|mu</div>
<div class="pre"><a id="l116" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l116" class="linenr"> 116</a> #&nbsp;&nbsp;&nbsp;Historgrams&nbsp;were&nbsp;generated&nbsp;in&nbsp;R&nbsp;(http://www.r-project.org/)&nbsp;based&nbsp;on&nbsp;the</div>
<div class="pre"><a id="l117" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l117" class="linenr"> 117</a> #&nbsp;&nbsp;&nbsp;calculations&nbsp;below&nbsp;and&nbsp;manually&nbsp;duplicated&nbsp;here.</div>
<div class="pre"><a id="l118" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l118" class="linenr"> 118</a> #</div>
<div class="pre"><a id="l119" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l119" class="linenr"> 119</a> #&nbsp;param:&nbsp;&nbsp;mu&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;mu&nbsp;is&nbsp;the&nbsp;mean&nbsp;of&nbsp;the&nbsp;distribution.</div>
<div class="pre"><a id="l120" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l120" class="linenr"> 120</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sigma&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;sigma&nbsp;is&nbsp;the&nbsp;standard&nbsp;deviation&nbsp;of&nbsp;the&nbsp;distribution.</div>
<div class="pre"><a id="l121" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l121" class="linenr"> 121</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;bounds[0]&nbsp;is&nbsp;the&nbsp;lower&nbsp;bound&nbsp;and&nbsp;bounds[1]</div>
<div class="pre"><a id="l122" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l122" class="linenr"> 122</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;is&nbsp;the&nbsp;upper&nbsp;bound.</div>
<div class="pre"><a id="l123" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l123" class="linenr"> 123</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;upperSkewed&nbsp;-&nbsp;if&nbsp;the&nbsp;distribution&nbsp;is&nbsp;upper&nbsp;skewed.</div>
<div class="pre"><a id="l124" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l124" class="linenr"> 124</a> #&nbsp;return:&nbsp;out&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Rondomly&nbsp;generated&nbsp;value&nbsp;from&nbsp;the&nbsp;skewed&nbsp;distribution.</div>
<div class="pre"><a id="l125" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l125" class="linenr"> 125</a> #</div>
<div class="pre"><a id="l126" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l126" class="linenr"> 126</a> #&nbsp;@todo:&nbsp;Because&nbsp;NumPy&#39;s&nbsp;random&nbsp;value&nbsp;generators&nbsp;are&nbsp;faster&nbsp;when&nbsp;called</div>
<div class="pre"><a id="l127" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l127" class="linenr"> 127</a> #&nbsp;&nbsp;&nbsp;a&nbsp;bunch&nbsp;of&nbsp;times&nbsp;at&nbsp;once,&nbsp;maybe&nbsp;allow&nbsp;this&nbsp;to&nbsp;generate&nbsp;and&nbsp;return</div>
<div class="pre"><a id="l128" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l128" class="linenr"> 128</a> #&nbsp;&nbsp;&nbsp;multiple&nbsp;values&nbsp;at&nbsp;once?</div>
<div class="pre"><a id="l129" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l129" class="linenr"> 129</a> </div>
<div class="pre"><a id="l130" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l130" class="linenr"> 130</a> </div>
<div class="pre"><a id="l131" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l131" class="linenr"> 131</a> def&nbsp;skewedGauss(mu,&nbsp;sigma,&nbsp;bounds,&nbsp;upperSkewed=True):</div>
<div class="pre"><a id="l132" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l132" class="linenr"> 132</a> &nbsp;&nbsp;&nbsp;&nbsp;raw&nbsp;=&nbsp;gauss(mu,&nbsp;sigma)</div>
<div class="pre"><a id="l133" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l133" class="linenr"> 133</a> </div>
<div class="pre"><a id="l134" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l134" class="linenr"> 134</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Quicker&nbsp;to&nbsp;check&nbsp;an&nbsp;extra&nbsp;condition&nbsp;than&nbsp;do&nbsp;unnecessary&nbsp;math.&nbsp;.&nbsp;.&nbsp;.</div>
<div class="pre"><a id="l135" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l135" class="linenr"> 135</a> &nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;raw&nbsp;&lt;&nbsp;mu&nbsp;and&nbsp;not&nbsp;upperSkewed:</div>
<div class="pre"><a id="l136" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l136" class="linenr"> 136</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out&nbsp;=&nbsp;((mu&nbsp;-&nbsp;bounds[0])&nbsp;/&nbsp;(3&nbsp;*&nbsp;sigma))&nbsp;*&nbsp;raw&nbsp;+&nbsp;((mu&nbsp;*&nbsp;(bounds[0]&nbsp;-&nbsp;(mu&nbsp;-&nbsp;3&nbsp;*&nbsp;sigma)))&nbsp;/&nbsp;(3&nbsp;*&nbsp;sigma))</div>
<div class="pre"><a id="l137" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l137" class="linenr"> 137</a> &nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;raw&nbsp;&gt;&nbsp;mu&nbsp;and&nbsp;upperSkewed:</div>
<div class="pre"><a id="l138" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l138" class="linenr"> 138</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out&nbsp;=&nbsp;((mu&nbsp;-&nbsp;bounds[1])&nbsp;/&nbsp;(3&nbsp;*&nbsp;-sigma))&nbsp;*&nbsp;raw&nbsp;+&nbsp;((mu&nbsp;*&nbsp;(bounds[1]&nbsp;-&nbsp;(mu&nbsp;+&nbsp;3&nbsp;*&nbsp;sigma)))&nbsp;/&nbsp;(3&nbsp;*&nbsp;-sigma))</div>
<div class="pre"><a id="l139" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l139" class="linenr"> 139</a> &nbsp;&nbsp;&nbsp;&nbsp;else:</div>
<div class="pre"><a id="l140" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l140" class="linenr"> 140</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out&nbsp;=&nbsp;raw</div>
<div class="pre"><a id="l141" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l141" class="linenr"> 141</a> </div>
<div class="pre"><a id="l142" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l142" class="linenr"> 142</a> &nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out</div>
<div class="pre"><a id="l143" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l143" class="linenr"> 143</a> </div>
<div class="pre"><a id="l144" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l144" class="linenr"> 144</a> </div>
<div class="pre"><a id="l145" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l145" class="linenr"> 145</a> #&nbsp;@todo&nbsp;create&nbsp;a&nbsp;def&nbsp;for&nbsp;generating&nbsp;an&nbsp;alpha&nbsp;and&nbsp;beta&nbsp;for&nbsp;a&nbsp;beta&nbsp;distribution</div>
<div class="pre"><a id="l146" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l146" class="linenr"> 146</a> #&nbsp;&nbsp;&nbsp;given&nbsp;a&nbsp;mu,&nbsp;sigma,&nbsp;and&nbsp;an&nbsp;upper&nbsp;and&nbsp;lower&nbsp;bound.&nbsp;&nbsp;This&nbsp;proved&nbsp;faster&nbsp;in</div>
<div class="pre"><a id="l147" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l147" class="linenr"> 147</a> #&nbsp;&nbsp;&nbsp;profiling&nbsp;in&nbsp;addition&nbsp;to&nbsp;providing&nbsp;a&nbsp;much&nbsp;better&nbsp;distribution&nbsp;curve</div>
<div class="pre"><a id="l148" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l148" class="linenr"> 148</a> #&nbsp;&nbsp;&nbsp;provided&nbsp;multiple&nbsp;iterations&nbsp;happen&nbsp;within&nbsp;this&nbsp;function;&nbsp;otherwise&nbsp;it&nbsp;was</div>
<div class="pre"><a id="l149" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l149" class="linenr"> 149</a> #&nbsp;&nbsp;&nbsp;slower.</div>
<div class="pre"><a id="l150" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l150" class="linenr"> 150</a> #&nbsp;&nbsp;&nbsp;This&nbsp;might&nbsp;be&nbsp;a&nbsp;scratch&nbsp;because&nbsp;of&nbsp;the&nbsp;bounds&nbsp;placed&nbsp;on&nbsp;mu&nbsp;and&nbsp;sigma:</div>
<div class="pre"><a id="l151" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l151" class="linenr"> 151</a> #</div>
<div class="pre"><a id="l152" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l152" class="linenr"> 152</a> #&nbsp;&nbsp;&nbsp;For&nbsp;alpha&nbsp;&gt;&nbsp;1&nbsp;and&nbsp;beta&nbsp;&gt;&nbsp;1:</div>
<div class="pre"><a id="l153" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l153" class="linenr"> 153</a> #&nbsp;&nbsp;&nbsp;mu^2&nbsp;-&nbsp;mu^3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mu^3&nbsp;-&nbsp;mu^2&nbsp;+&nbsp;mu</div>
<div class="pre"><a id="l154" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l154" class="linenr"> 154</a> #&nbsp;&nbsp;&nbsp;-----------&nbsp;&lt;&nbsp;sigma&nbsp;&lt;&nbsp;----------------</div>
<div class="pre"><a id="l155" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l155" class="linenr"> 155</a> #&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1&nbsp;+&nbsp;mu&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2&nbsp;-&nbsp;mu</div>
<div class="pre"><a id="l156" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l156" class="linenr"> 156</a> #</div>
<div class="pre"><a id="l157" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l157" class="linenr"> 157</a> #&nbsp;def&nbsp;generateBeta(mu,&nbsp;sigma,&nbsp;scale,&nbsp;repitions=1):</div>
<div class="pre"><a id="l158" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l158" class="linenr"> 158</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;results&nbsp;=&nbsp;[]</div>
<div class="pre"><a id="l159" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l159" class="linenr"> 159</a> #</div>
<div class="pre"><a id="l160" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/HEAD:/add_mesh_rocks/utils.py#l160" class="linenr"> 160</a> &nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;return&nbsp;results</div>
</div><div class="page_footer">
<div class="page_footer_text">This project founded to maintain a central repository of Blender contrib addons</div>
<a class="rss_logo" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/rss?f=add_mesh_rocks/utils.py" title="history of add_mesh_rocks/utils.py RSS feed">RSS</a>
<a class="rss_logo" href="https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/atom?f=add_mesh_rocks/utils.py" title="history of add_mesh_rocks/utils.py Atom feed">Atom</a>
</div>
<script type="text/javascript" src="static/gitweb.js"></script>
<script type="text/javascript">
window.onload = function () {
	var tz_cookie = { name: 'gitweb_tz', expires: 14, path: '/' };
	onloadTZSetup('local', tz_cookie, 'datetime');
};
</script>
</body>
</html>